import type { Metadata } from "next";
import { Roboto } from "next/font/google";

//components
import SideNavation from "@/components/common/navigation/SideNavation";
//Shadcn UI
import { Toaster } from "@/components/ui/sonner";
import "@/styles/globals.css";
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Shadcn UI - Todoboard",
  description: "Generated by lunar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SideNavation />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
